### ISSUE TITLE
Lowercase vs. Uppercase M in market.js causes bugs in ubuntu

### ISSUE THREAD

**Issue by alexander-morris** [alenkart/node-crypto-api#1]
Sort of a random bug, but it seems that running on ubuntu with node 6.11.5 it seems to not include market.js properly (from the lib folder) when kraken.js and the other market files load. 

As a result, I was getting a bug like 
`module.js:471
    throw err;
    ^

Error: Cannot find module './Market'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/depositController/node_modules/node-crypto-api/lib/kraken.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

I was able to resolve this by just cloning market.js to Market.js for now, but it would be nice to know why this happens 

All in all, awesome module and really enjoying using it though :)  great work! 👍 🥇 

Update:
On further research, it appears that this is actually an OS related issue and not an NPM problem. https://stackoverflow.com/questions/13617863/can-i-force-node-js-require-to-be-case-sensitive

Linux based systems use case sensitive file names, so the require statements should all be made to match the actual file names or they'll always fail.

I'll try to PR this if I have some time :)

**Comment by alenkart** [comment]
Merged

**Comment by alenkart** [comment]
Sorry for the late answer and thanks for the contribution. I merged the code and publish a new version of the library on npm (1.0.8).
